---

- name: Packages key is installed
  apt_key:
    data: "{{ lookup('file', 'opscenter.key') }}"
    state: present

- name: Packages list is available
  copy:
    src: opscenter.list
    dest: /etc/apt/sources.list.d/opscenter.list
    owner: root
    group: root
    mode: 0644
  register: opscenter_apt_sources

- name: Packages list is up to date (if sources were added)
  apt:
    update_cache: yes
  when: opscenter_apt_sources.changed

- name: Packages list is up to date (if cache expired)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Packages are installed
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - opscenter

- name: Service is started
  service:
    name: opscenterd
    state: started
