---

- name: Service is stopped
  service:
    name: cassandra
    state: stopped

- name: Data is removed
  file:
    path: /var/lib/cassandra/data/system
    state: absent

- name: Cassandra is configured
  template:
    src: cassandra.yml
    dest: /etc/cassandra/cassandra.yml
