---

- name: Packages key is installed
  apt_key:
    data: "{{ lookup('file', 'cassandra.key') }}"
    state: present

- name: Packages list is available
  copy:
    src: cassandra.list
    dest: /etc/apt/sources.list.d/cassandra.list
    owner: root
    group: root
    mode: 0644
  register: cassandra_apt_sources

- name: Packages list is up to date (if sources were added)
  apt:
    update_cache: yes
  when: cassandra_apt_sources.changed

- name: Packages list is up to date (if cache expired)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Packages are installed
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - cassandra

- name: Node either bootstrapped already or is ready for bootstrapping
  include: pre_bootstrap_1.yml

- name: Default configuration is backed up
  shell: cp /etc/cassandra/cassandra.yaml /etc/cassandra/cassandra.yaml.default
  args:
    creates: /etc/cassandra/cassandra.yaml.default

- name: Custom configuration is installed
  template:
    src: cassandra.yaml
    dest: /etc/cassandra/cassandra.yaml
    owner: root
    group: root
    mode: 0644
