---

- name: Packages key is installed
  apt_key:
    data: "{{ lookup('file', 'cassandra.key') }}"
    state: present

- name: Packages list is available
  copy:
    src: cassandra.list
    dest: /etc/apt/sources.list.d/cassandra.list
    owner: root
    group: root
    mode: 0644
  register: cassandra_apt_sources

- name: Packages list is up to date (if sources were added)
  apt:
    update_cache: yes
  when: cassandra_apt_sources.changed

- name: Packages list is up to date (if cache expired)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Packages are installed
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - cassandra

# Uncomment to reset all nodes (DANGER!)
#- file: path=/etc/cassandra/.configured state=absent

- name: Check if node is configured
  stat:
    path: /etc/cassandra/.configured
  register: cassandra_configured
  changed_when: False

- name: Node is reset if not configured
  include: reset.yml
  when: not cassandra_configured.stat.exists

- name: Default configuration is backed up
  shell: cp /etc/cassandra/cassandra.yaml /etc/cassandra/cassandra.yaml.default
  args:
    creates: /etc/cassandra/cassandra.yaml.default

- name: Custom configuration is installed
  template:
    src: cassandra.yaml
    dest: /etc/cassandra/cassandra.yaml
    owner: root
    group: root
    mode: 0644

- name: Node is marked as configured
  file:
    path: /etc/cassandra/.configured
    state: touch
  when: not cassandra_configured.stat.exists
