---

- name: Generate cluster CA
  shell: "./gen_cluster.sh {{cassandra_cluster}} {{cassandra_truststore_password}}"
  args:
    chdir: playbooks/roles/cassandra-certs/files
    creates: "{{cassandra_cluster}}/cluster-truststore.jks"

- name: Generate nodes keys
  shell: "./gen_node.sh {{cassandra_cluster}} {{item}} {{cassandra_keystore_password}}"
  args:
    chdir: playbooks/roles/cassandra-certs/files
    creates: "{{cassandra_cluster}}/{{item}}-keystore.jks"
  with_items: groups.cassandra
